# Generated by Django 5.2.5 on 2025-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='study_lang',
            field=models.CharField(choices=[('UZBEK', 'Uzbek'), ('RUSSIAN', 'Russian'), ('ENGLISH', 'English')], default='UZBEK', max_length=20),
        ),
    ]
