# Generated by Django 5.2.4 on 2025-08-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='room_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
