# Generated by Django 5.2.4 on 2025-08-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_class_curator_class_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.class'),
        ),
    ]
